
if __name__ == '__main__':
    try:
       pass
    except Exception as e:
        print(f'При выполнении произошла ошибка: {e}')

